# Ex - GroupBy

In [1]:
# import pandas
import pandas as pd

class display(object):
    """Display HTML representation of multiple objects"""
    
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [37]:
drinks = pd.read_csv("/Users/jorgeshz/Data Science Bootcamp/DS-Repo-JorgeSanchez/02_Herramientas_Avanzadas/02_Pandas/02_Practica/03_Grouping/Alcohol_Consumption/drinks.csv")

### Step 3. Assign it to a variable called drinks.

In [38]:
display("drinks")
drinks

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
...,...,...,...,...,...,...
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

En primer lugar, debemos ver si hay NAs

In [39]:
drinks.isna().sum() #Vemos que faltan datos en la columna de continentes. Que podemos rellenar nosotros mismos

country                          0
beer_servings                    0
spirit_servings                  0
wine_servings                    0
total_litres_of_pure_alcohol     0
continent                       23
dtype: int64

In [40]:
drinks.loc[drinks['continent'].isnull(), 'country'] #Son países de Norteamerica/Centroamerica

5                 Antigua & Barbuda
11                          Bahamas
14                         Barbados
17                           Belize
32                           Canada
41                       Costa Rica
43                             Cuba
50                         Dominica
51               Dominican Republic
54                      El Salvador
68                          Grenada
69                        Guatemala
73                            Haiti
74                         Honduras
84                          Jamaica
109                          Mexico
122                       Nicaragua
130                          Panama
143               St. Kitts & Nevis
144                       St. Lucia
145    St. Vincent & the Grenadines
174               Trinidad & Tobago
184                             USA
Name: country, dtype: str

In [44]:
drinks["continent"] = drinks["continent"].fillna("NA")

In [ ]:
drinks.isna().sum() #lo hemos actualizado

country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
continent                       0
dtype: int64

### Step 4. Which continent drinks more beer on average?

In [46]:
beer_per_continent = drinks.groupby('continent')['beer_servings'].mean().round(2)
beer_per_continent

continent
AF     61.47
AS     37.05
EU    193.78
NA    145.43
OC     89.69
SA    175.08
Name: beer_servings, dtype: float64

Europa

In [47]:
print(beer_per_continent.loc['EU'])

193.78

### Step 5. For each continent print the statistics for wine consumption.

In [48]:
continent_wine_stats = drinks.groupby('continent')['wine_servings'].describe().round(2)
continent_wine_stats

           count    mean    std  min   25%    50%     75%    max
continent
AF          53.0   16.26  38.85  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.07  21.67  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.22  97.42  0.0  59.0  128.0  195.00  370.0
NA          23.0   24.52  28.27  1.0   5.0   11.0   34.00  100.0
OC          16.0   35.62  64.56  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.42  88.62  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [49]:
mean_alcohol_continent = drinks.groupby("continent").mean(numeric_only= True).round(2)
mean_alcohol_continent

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.47,16.34,16.26,3.01
AS,37.05,60.84,9.07,2.17
EU,193.78,132.56,142.22,8.62
NA,145.43,165.74,24.52,6.00
OC,89.69,58.44,35.62,3.38
SA,175.08,114.75,62.42,6.31

### Step 7. Print the median alcohol consumption per continent for every column

In [50]:
median_alcohol_continent  = drinks.groupby('continent').median(numeric_only=True).round(2)
median_alcohol_continent

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
NA,143.0,137.0,11.0,6.30
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [51]:
min_max_mean_spirit = drinks.groupby('continent')['spirit_servings'].agg(['mean','min','max']).round(2)
min_max_mean_spirit

             mean  min  max
continent
AF          16.34    0  152
AS          60.84    0  326
EU         132.56    0  373
NA         165.74   68  438
OC          58.44    0  254
SA         114.75   25  302