# Occupation

In [2]:
import pandas as pd 
import random as random 


class display(object):
    """Display HTML representation of multiple objects"""
    
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [3]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep = "|")

In [4]:
users.set_index("user_id", inplace= True)

### Step 4. Discover what is the mean age per occupation

In [5]:
users.groupby('occupation')['age'].mean().round(1)

#el transform es el groupby desenrollado
#sin las mismas dimensiones no se pueen juntar

occupation
administrator    38.7
artist           31.4
doctor           43.6
educator         42.0
engineer         36.4
entertainment    29.2
executive        38.7
healthcare       41.6
homemaker        32.6
lawyer           36.8
librarian        40.0
marketing        37.6
none             26.6
other            34.5
programmer       33.1
retired          63.1
salesman         35.7
scientist        35.5
student          22.1
technician       33.1
writer           36.3
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [6]:
male_ratio = users.groupby(['occupation','gender'])['age'].count()

In [7]:

male_ratio = users.groupby('occupation')['gender'].apply(lambda x: (x == 'M').sum() / x.count())

male_ratio_sorted = male_ratio.sort_values(ascending=False)

print(male_ratio_sorted)

occupation
doctor           1.000000
engineer         0.970149
technician       0.962963
retired          0.928571
programmer       0.909091
executive        0.906250
scientist        0.903226
entertainment    0.888889
lawyer           0.833333
salesman         0.750000
educator         0.726316
student          0.693878
other            0.657143
marketing        0.615385
writer           0.577778
none             0.555556
administrator    0.544304
artist           0.535714
librarian        0.431373
healthcare       0.312500
homemaker        0.142857
Name: gender, dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [9]:
age_ranges = users.groupby(['occupation'])['age'].agg(
    min_age ='min',
    max_age = 'max'
    ) .sort_values(by= 'min_age')

age_ranges

               min_age  max_age
occupation
student              7       42
none                11       55
other               13       64
entertainment       15       50
writer              18       60
salesman            18       66
artist              19       48
programmer          20       63
homemaker           20       50
technician          21       55
administrator       21       70
lawyer              21       53
healthcare          22       62
executive           22       69
engineer            22       70
educator            23       63
scientist           23       55
librarian           23       69
marketing           24       55
doctor              28       64
retired             51       73

### Step 7. For each combination of occupation and gender, calculate the mean age

In [12]:
occupation_and_gender_mean_age = users.groupby(['occupation', 'gender'])['age'].mean().round(1)

occupation_and_gender_mean_age

occupation     gender
administrator  F         40.6
               M         37.2
artist         F         30.3
               M         32.3
doctor         M         43.6
educator       F         39.1
               M         43.1
engineer       F         29.5
               M         36.6
entertainment  F         31.0
               M         29.0
executive      F         44.0
               M         38.2
healthcare     F         39.8
               M         45.4
homemaker      F         34.2
               M         23.0
lawyer         F         39.5
               M         36.2
librarian      F         40.0
               M         40.0
marketing      F         37.2
               M         37.9
none           F         36.5
               M         18.6
other          F         35.5
               M         34.0
programmer     F         32.2
               M         33.2
retired        F         70.0
               M         62.5
salesman       F         27.0
               M         38.6
scientist      F         28.3
               M         36.3
student        F         20.8
               M         22.7
technician     F         38.0
               M         33.0
writer         F         37.6
               M         35.3
Name: age, dtype: float64

### Step 8.  For each occupation present the percentage of women and men

In [14]:

occ_percent = users.groupby('occupation')['gender'].value_counts(normalize=True) * 100
occ_percent = occ_percent.unstack().fillna(0).round(2)

occ_percent

gender             F       M
occupation
administrator  45.57   54.43
artist         46.43   53.57
doctor          0.00  100.00
educator       27.37   72.63
engineer        2.99   97.01
entertainment  11.11   88.89
executive       9.38   90.62
healthcare     68.75   31.25
homemaker      85.71   14.29
lawyer         16.67   83.33
librarian      56.86   43.14
marketing      38.46   61.54
none           44.44   55.56
other          34.29   65.71
programmer      9.09   90.91
retired         7.14   92.86
salesman       25.00   75.00
scientist       9.68   90.32
student        30.61   69.39
technician      3.70   96.30
writer         42.22   57.78