# Occupation

In [4]:
import pandas as pd 
import random as random 


class display(object):
    """Display HTML representation of multiple objects"""
    
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [5]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep = "|")

In [7]:
users.set_index("user_id", inplace= True)

### Step 4. Discover what is the mean age per occupation

In [12]:
users.groupby('occupation')['age'].mean().round(1)

occupation
administrator    38.7
artist           31.4
doctor           43.6
educator         42.0
engineer         36.4
entertainment    29.2
executive        38.7
healthcare       41.6
homemaker        32.6
lawyer           36.8
librarian        40.0
marketing        37.6
none             26.6
other            34.5
programmer       33.1
retired          63.1
salesman         35.7
scientist        35.5
student          22.1
technician       33.1
writer           36.3
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [ ]:
male_ratio = users.groupby('occupation')['gender'].apply(lambda x: (x == "M").mean()).reset_index(name = "male_ratio")

In [27]:

male_ratio = (users['gender'] == 'M').groupby(users['occupation']).mean().reset_index(name='male_ratio').round()

In [24]:
male_ratio.sort_values(by = "male_ratio", ascending= False)

       occupation  male_ratio
2          doctor    1.000000
4        engineer    0.970149
19     technician    0.962963
15        retired    0.928571
14     programmer    0.909091
6       executive    0.906250
17      scientist    0.903226
5   entertainment    0.888889
9          lawyer    0.833333
16       salesman    0.750000
3        educator    0.726316
18        student    0.693878
13          other    0.657143
11      marketing    0.615385
20         writer    0.577778
12           none    0.555556
0   administrator    0.544304
1          artist    0.535714
10      librarian    0.431373
7      healthcare    0.312500
8       homemaker    0.142857

### Step 6. For each occupation, calculate the minimum and maximum ages

               min  max
occupation
administrator   21   70
artist          19   48
doctor          28   64
educator        23   63
engineer        22   70
entertainment   15   50
executive       22   69
healthcare      22   62
homemaker       20   50
lawyer          21   53
librarian       23   69
marketing       24   55
none            11   55
other           13   64
programmer      20   63
retired         51   73
salesman        18   66
scientist       23   55
student          7   42
technician      21   55
writer          18   60

### Step 7. For each combination of occupation and gender, calculate the mean age

                            age
occupation    gender
administrator F       40.638889
              M       37.162791
artist        F       30.307692
              M       32.333333
doctor        M       43.571429
educator      F       39.115385
              M       43.101449
engineer      F       29.500000
              M       36.600000
entertainment F       31.000000
              M       29.000000
executive     F       44.000000
              M       38.172414
healthcare    F       39.818182
              M       45.400000
homemaker     F       34.166667
              M       23.000000
lawyer        F       39.500000
              M       36.200000
librarian     F       40.000000
              M       40.000000
marketing     F       37.200000
              M       37.875000
none          F       36.500000
              M       18.600000
other         F       35.472222
              M       34.028986
programmer    F       32.166667
              M       33.216667
retired       F       70.000000
              M       62.538462
salesman      F       27.000000
              M       38.555556
scientist     F       28.333333
              M       36.321429
student       F       20.750000
              M       22.669118
technician    F       38.000000
              M       32.961538
writer        F       37.631579
              M       35.346154

### Step 8.  For each occupation present the percentage of women and men

occupation     gender
administrator  M          54.430380
               F          45.569620
artist         M          53.571429
               F          46.428571
doctor         M         100.000000
educator       M          72.631579
               F          27.368421
engineer       M          97.014925
               F           2.985075
entertainment  M          88.888889
               F          11.111111
executive      M          90.625000
               F           9.375000
healthcare     F          68.750000
               M          31.250000
homemaker      F          85.714286
               M          14.285714
lawyer         M          83.333333
               F          16.666667
librarian      F          56.862745
               M          43.137255
marketing      M          61.538462
               F          38.461538
none           M          55.555556
               F          44.444444
other          M          65.714286
               F          34.285714
programmer     M          90.909091
               F           9.090909
retired        M          92.857143
               F           7.142857
salesman       M          75.000000
               F          25.000000
scientist      M          90.322581
               F           9.677419
student        M          69.387755
               F          30.612245
technician     M          96.296296
               F           3.703704
writer         M          57.777778
               F          42.222222
Name: gender, dtype: float64