# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [10]:
import pandas as pd
import random as random

class display(object):
    """Display HTML representation of multiple objects"""
    
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [12]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep = "\t")

### Step 3. Assign it to a variable called chipo.

In [15]:
display("chipo")

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

# Name of the max valued product

In [16]:
#Hay q cambiar los precos a numeros
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

In [26]:
max_val_prod = chipo.loc[chipo['item_price'].idxmax(), 'item_name']
precio_max = chipo.item_price.max()
print(f"El producto más caro es {max_val_prod} y vale {precio_max}$")

El producto más caro es Chips and Fresh Tomato Salsa y vale 44.25$

### Step 4. How many products cost more than $10.00?

In [29]:
print(chipo[chipo.item_price > 10].item_name.count())

1130

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [36]:
chipo[['item_name', 'item_price']]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [38]:
chipo.sort_values(by="item_name")

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

V1

In [45]:
q_max = chipo.loc[chipo['item_price'].idxmax(), 'quantity']

print(q_max)

15

V2

In [46]:
chipo.loc[chipo['item_price'].idxmax(), ['item_price', 'quantity']]

item_price    44.25
quantity      15.00
Name: 3598, dtype: float64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [51]:
chipo[chipo['item_name'] == "Veggie Salad Bowl"].value_counts().sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [62]:
canned_soda_orders = chipo[(chipo['item_name'] == 'Canned Soda') 
                  & (chipo['quantity'] > 1)]

print(len(canned_soda_orders))

20

In [ ]:
# Filter for item_name 'Canned Soda' and quantity greater than 1
canned_soda_orders = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]

# Get the number of times this occurred
print(len(canned_soda_orders))
# Output: 20